import { LevelConfig } from '../types';

export const LEVELS: LevelConfig[] = [
  // Level 1: 雙影初醒 (First Fold)
  {
    id: 1,
    name: '雙影初醒',
    subName: 'FIRST FOLD',
    description: '教學關卡：第 1 輪特工踩住壓力踏板直至時間倒數完畢；第 2 輪殘影會替你踩踏板開門，本體衝入取得核心撤離！',
    maxLoops: 2,
    loopDuration: 12.0,
    spawn: { x: 140, y: 270, angle: 0 },
    core: { x: 800, y: 270 },
    exit: { x: 800, y: 130 },
    walls: [
      // 外框
      { x: 0, y: 0, w: 960, h: 40 },
      { x: 0, y: 500, w: 960, h: 40 },
      { x: 0, y: 0, w: 40, h: 540 },
      { x: 920, y: 0, w: 40, h: 540 },
      // 分隔隔牆 (中央豎牆，中間留出閘門口)
      { x: 500, y: 40, w: 30, h: 160 },
      { x: 500, y: 320, w: 30, h: 180 },
    ],
    pads: [
      {
        id: 'pad-1',
        x: 300,
        y: 400,
        radius: 26,
        targets: ['door-1'],
        isPressed: false,
        holdTimer: 0,
        color: '#00f0ff',
      },
    ],
    doors: [
      {
        id: 'door-1',
        x: 500,
        y: 200,
        w: 30,
        h: 120,
        isOpen: false,
        openProgress: 0,
        orientation: 'vertical',
      },
    ],
    lasers: [],
  },

  // Level 2: 雙重連動 (Dual Interlock)
  {
    id: 2,
    name: '雙重連動',
    subName: 'DUAL INTERLOCK',
    description: '兩道閘門被不同踏板鎖定。Loop 1 踩 A，Loop 2 穿過 A 踩 B，Loop 3 雙影齊踏，奪取核心！',
    maxLoops: 3,
    loopDuration: 12.0,
    spawn: { x: 120, y: 150, angle: 0 },
    core: { x: 820, y: 410 },
    exit: { x: 820, y: 140 },
    walls: [
      // 外框
      { x: 0, y: 0, w: 960, h: 40 },
      { x: 0, y: 500, w: 960, h: 40 },
      { x: 0, y: 0, w: 40, h: 540 },
      { x: 920, y: 0, w: 40, h: 540 },
      // 隔牆 1 (左至中)
      { x: 360, y: 40, w: 26, h: 180 },
      { x: 360, y: 320, w: 26, h: 180 },
      // 隔牆 2 (中至右)
      { x: 680, y: 40, w: 26, h: 160 },
      { x: 680, y: 300, w: 26, h: 200 },
    ],
    pads: [
      {
        id: 'pad-1',
        x: 200,
        y: 400,
        radius: 26,
        targets: ['door-1'],
        isPressed: false,
        holdTimer: 0,
        color: '#00f0ff',
      },
      {
        id: 'pad-2',
        x: 520,
        y: 130,
        radius: 26,
        targets: ['door-2'],
        isPressed: false,
        holdTimer: 0,
        color: '#c040ff',
      },
    ],
    doors: [
      {
        id: 'door-1',
        x: 360,
        y: 220,
        w: 26,
        h: 100,
        isOpen: false,
        openProgress: 0,
        orientation: 'vertical',
      },
      {
        id: 'door-2',
        x: 680,
        y: 200,
        w: 26,
        h: 100,
        isOpen: false,
        openProgress: 0,
        orientation: 'vertical',
      },
    ],
    lasers: [],
  },

  // Level 3: 雷射廊道 (Laser Hazard)
  {
    id: 3,
    name: '雷射廊道',
    subName: 'LASER HAZARD',
    description: '金庫通道中佈設了高壓脈衝雷射。特工可利用 Space 鍵閃爍衝刺，或由殘影踩下踏板永久癱瘓雷射！',
    maxLoops: 3,
    loopDuration: 12.0,
    spawn: { x: 110, y: 270, angle: 0 },
    core: { x: 840, y: 270 },
    exit: { x: 110, y: 410 },
    walls: [
      // 外框
      { x: 0, y: 0, w: 960, h: 40 },
      { x: 0, y: 500, w: 960, h: 40 },
      { x: 0, y: 0, w: 40, h: 540 },
      { x: 920, y: 0, w: 40, h: 540 },
      // 上下走廊阻隔
      { x: 280, y: 160, w: 440, h: 24 },
      { x: 280, y: 360, w: 440, h: 24 },
      // 終端閘門
      { x: 740, y: 184, w: 24, h: 80 },
    ],
    pads: [
      {
        id: 'pad-laser-disable',
        x: 200,
        y: 100,
        radius: 26,
        targets: ['door-core'],
        isPressed: false,
        holdTimer: 0,
        color: '#ffaa00',
      },
    ],
    doors: [
      {
        id: 'door-core',
        x: 740,
        y: 264,
        w: 24,
        h: 96,
        isOpen: false,
        openProgress: 0,
        orientation: 'vertical',
      },
    ],
    lasers: [
      {
        id: 'laser-1',
        x1: 420,
        y1: 184,
        x2: 420,
        y2: 360,
        isActive: true,
        cycleTime: 2.4,
        onDuration: 1.4,
        offDuration: 1.0,
        timer: 0,
      },
      {
        id: 'laser-2',
        x1: 580,
        y1: 184,
        x2: 580,
        y2: 360,
        isActive: true,
        cycleTime: 2.4,
        onDuration: 1.4,
        offDuration: 1.0,
        timer: 1.2,
      },
    ],
  },

  // Level 4: 時序接力 (Chrono Relay)
  {
    id: 4,
    name: '時序接力',
    subName: 'CHRONO RELAY',
    description: '遙遠的踏板無法由同一人踩踏並及時通過！Loop 1 專心跑向踏板並站定，Loop 2 提前在門前就位衝刺！',
    maxLoops: 3,
    loopDuration: 12.0,
    spawn: { x: 100, y: 440, angle: -Math.PI / 2 },
    core: { x: 820, y: 100 },
    exit: { x: 820, y: 440 },
    walls: [
      // 外框
      { x: 0, y: 0, w: 960, h: 40 },
      { x: 0, y: 500, w: 960, h: 40 },
      { x: 0, y: 0, w: 40, h: 540 },
      { x: 920, y: 0, w: 40, h: 540 },
      // 迂迴迷宮牆
      { x: 220, y: 160, w: 30, h: 340 },
      { x: 440, y: 40, w: 30, h: 360 },
      { x: 680, y: 180, w: 30, h: 320 },
    ],
    pads: [
      {
        id: 'pad-relay',
        x: 120,
        y: 100,
        radius: 26,
        targets: ['door-relay-1', 'door-relay-2'],
        isPressed: false,
        holdTimer: 0,
        color: '#00f0ff',
      },
    ],
    doors: [
      {
        id: 'door-relay-1',
        x: 440,
        y: 400,
        w: 30,
        h: 100,
        isOpen: false,
        openProgress: 0,
        orientation: 'vertical',
      },
      {
        id: 'door-relay-2',
        x: 680,
        y: 80,
        w: 30,
        h: 100,
        isOpen: false,
        openProgress: 0,
        orientation: 'vertical',
      },
    ],
    lasers: [
      {
        id: 'laser-relay',
        x1: 250,
        y1: 280,
        x2: 440,
        y2: 280,
        isActive: true,
        cycleTime: 2.0,
        onDuration: 1.0,
        offDuration: 1.0,
        timer: 0.5,
      },
    ],
  },

  // Level 5: 三角悖論 (Trinity Matrix)
  {
    id: 5,
    name: '三角悖論',
    subName: 'TRINITY MATRIX',
    description: '三位一體！三個壓力踏板相互解鎖三個安全分區。善用三個殘影各司其職，完成最後的大脫逃。',
    maxLoops: 4,
    loopDuration: 12.0,
    spawn: { x: 100, y: 100, angle: 0 },
    core: { x: 480, y: 270 },
    exit: { x: 850, y: 450 },
    walls: [
      // 外框
      { x: 0, y: 0, w: 960, h: 40 },
      { x: 0, y: 500, w: 960, h: 40 },
      { x: 0, y: 0, w: 40, h: 540 },
      { x: 920, y: 0, w: 40, h: 540 },
      // 十字迷宮壁
      { x: 300, y: 40, w: 24, h: 180 },
      { x: 300, y: 320, w: 24, h: 180 },
      { x: 630, y: 40, w: 24, h: 180 },
      { x: 630, y: 320, w: 24, h: 180 },
      { x: 300, y: 210, w: 120, h: 24 },
      { x: 540, y: 210, w: 114, h: 24 },
    ],
    pads: [
      {
        id: 'pad-A',
        x: 120,
        y: 430,
        radius: 26,
        targets: ['door-A'],
        isPressed: false,
        holdTimer: 0,
        color: '#00f0ff',
      },
      {
        id: 'pad-B',
        x: 480,
        y: 100,
        radius: 26,
        targets: ['door-B'],
        isPressed: false,
        holdTimer: 0,
        color: '#c040ff',
      },
      {
        id: 'pad-C',
        x: 480,
        y: 430,
        radius: 26,
        targets: ['door-C'],
        isPressed: false,
        holdTimer: 0,
        color: '#ffaa00',
      },
    ],
    doors: [
      {
        id: 'door-A',
        x: 300,
        y: 220,
        w: 24,
        h: 100,
        isOpen: false,
        openProgress: 0,
        orientation: 'vertical',
      },
      {
        id: 'door-B',
        x: 420,
        y: 210,
        w: 120,
        h: 24,
        isOpen: false,
        openProgress: 0,
        orientation: 'horizontal',
      },
      {
        id: 'door-C',
        x: 630,
        y: 220,
        w: 24,
        h: 100,
        isOpen: false,
        openProgress: 0,
        orientation: 'vertical',
      },
    ],
    lasers: [
      {
        id: 'laser-tri-1',
        x1: 654,
        y1: 150,
        x2: 920,
        y2: 150,
        isActive: true,
        cycleTime: 2.2,
        onDuration: 1.2,
        offDuration: 1.0,
        timer: 0.2,
      },
    ],
  },

  // Level 6: 量子金庫 (The Vault: Paradox)
  {
    id: 6,
    name: '量子金庫',
    subName: 'THE VAULT: PARADOX',
    description: '終極挑戰！旋轉防禦雷射、雙重重力門與極限 12 秒壓哨逃脫，只有時空大師特工才能全身而退！',
    maxLoops: 4,
    loopDuration: 12.0,
    spawn: { x: 90, y: 270, angle: 0 },
    core: { x: 740, y: 270 },
    exit: { x: 90, y: 100 },
    walls: [
      // 外框
      { x: 0, y: 0, w: 960, h: 40 },
      { x: 0, y: 500, w: 960, h: 40 },
      { x: 0, y: 0, w: 40, h: 540 },
      { x: 920, y: 0, w: 40, h: 540 },
      // 內圈金庫四方牆
      { x: 260, y: 150, w: 24, h: 240 },
      { x: 620, y: 150, w: 24, h: 240 },
      { x: 260, y: 150, w: 150, h: 24 },
      { x: 494, y: 150, w: 150, h: 24 },
      { x: 260, y: 366, w: 150, h: 24 },
      { x: 494, y: 366, w: 150, h: 24 },
    ],
    pads: [
      {
        id: 'vault-pad-1',
        x: 160,
        y: 430,
        radius: 26,
        targets: ['vault-door-top'],
        isPressed: false,
        holdTimer: 0,
        color: '#00f0ff',
      },
      {
        id: 'vault-pad-2',
        x: 450,
        y: 80,
        radius: 26,
        targets: ['vault-door-right'],
        isPressed: false,
        holdTimer: 0,
        color: '#c040ff',
      },
    ],
    doors: [
      {
        id: 'vault-door-top',
        x: 410,
        y: 150,
        w: 84,
        h: 24,
        isOpen: false,
        openProgress: 0,
        orientation: 'horizontal',
      },
      {
        id: 'vault-door-right',
        x: 620,
        y: 220,
        w: 24,
        h: 100,
        isOpen: false,
        openProgress: 0,
        orientation: 'vertical',
      },
    ],
    lasers: [
      {
        id: 'vault-laser-1',
        x1: 284,
        y1: 270,
        x2: 620,
        y2: 270,
        isActive: true,
        cycleTime: 2.6,
        onDuration: 1.3,
        offDuration: 1.3,
        timer: 0,
      },
      {
        id: 'vault-laser-2',
        x1: 450,
        y1: 174,
        x2: 450,
        y2: 366,
        isActive: true,
        cycleTime: 2.6,
        onDuration: 1.3,
        offDuration: 1.3,
        timer: 1.3,
      },
    ],
  },

  // Level 7: 傳送接力 (Portal Relay)
  {
    id: 7,
    name: '傳送接力',
    subName: 'PORTAL RELAY',
    description: '殘影需在特定秒數踩住傳送引導點為量子門充能，特工本體瞬間躍遷穿透合金密室奪取核心！',
    maxLoops: 3,
    loopDuration: 12.0,
    spawn: { x: 120, y: 270, angle: 0 },
    core: { x: 800, y: 140 },
    exit: { x: 800, y: 430 },
    walls: [
      // 外框
      { x: 0, y: 0, w: 960, h: 40 },
      { x: 0, y: 500, w: 960, h: 40 },
      { x: 0, y: 0, w: 40, h: 540 },
      { x: 920, y: 0, w: 40, h: 540 },
      // 中央縱向不可跨越重牆
      { x: 480, y: 40, w: 28, h: 460 },
      // 右側上下房間隔牆
      { x: 508, y: 270, w: 312, h: 24 },
    ],
    pads: [
      {
        id: 'pad-portal-prime',
        x: 200,
        y: 430,
        radius: 26,
        targets: [],
        isPressed: false,
        holdTimer: 0,
        color: '#00f0ff',
      },
      {
        id: 'pad-vault-door',
        x: 850,
        y: 200,
        radius: 24,
        targets: ['door-vault-pass'],
        isPressed: false,
        holdTimer: 0,
        color: '#ffe600',
      },
    ],
    doors: [
      {
        id: 'door-vault-pass',
        x: 820,
        y: 270,
        w: 100,
        h: 24,
        isOpen: false,
        openProgress: 0,
        orientation: 'horizontal',
      },
    ],
    lasers: [
      {
        id: 'laser-portal-corridor',
        x1: 280,
        y1: 140,
        x2: 480,
        y2: 140,
        isActive: true,
        cycleTime: 2.4,
        onDuration: 1.2,
        offDuration: 1.2,
        timer: 0,
      },
    ],
    teleporters: [
      {
        id: 'portal-alpha',
        x: 380,
        y: 270,
        targetX: 620,
        targetY: 140,
        radius: 28,
        requiresPadId: 'pad-portal-prime',
        isActive: false,
        color: '#00f0ff',
      },
    ],
    threeStarLoops: 2,
    threeStarMinTime: 3.5,
  },

  // Level 8: 電磁脈衝 (EMP Sequencer)
  {
    id: 8,
    name: '電磁脈衝',
    subName: 'EMP SEQUENCER',
    description: '核心被全向高能激光重重封鎖！三名殘影需在 3 秒窗口內同時啟動 3 個 EMP 電極，引發全場電磁脈衝癱瘓護盾！',
    maxLoops: 4,
    loopDuration: 12.0,
    spawn: { x: 120, y: 270, angle: 0 },
    core: { x: 480, y: 270 },
    exit: { x: 860, y: 270 },
    walls: [
      // 外框
      { x: 0, y: 0, w: 960, h: 40 },
      { x: 0, y: 500, w: 960, h: 40 },
      { x: 0, y: 0, w: 40, h: 540 },
      { x: 920, y: 0, w: 40, h: 540 },
      // 內圈中央護欄
      { x: 380, y: 170, w: 200, h: 20 },
      { x: 380, y: 350, w: 200, h: 20 },
    ],
    pads: [],
    doors: [],
    lasers: [
      {
        id: 'emp-laser-1',
        x1: 370,
        y1: 190,
        x2: 370,
        y2: 350,
        isActive: true,
      },
      {
        id: 'emp-laser-2',
        x1: 590,
        y1: 190,
        x2: 590,
        y2: 350,
        isActive: true,
      },
      {
        id: 'emp-laser-3',
        x1: 370,
        y1: 270,
        x2: 590,
        y2: 270,
        isActive: true,
      },
    ],
    empTerminals: [
      {
        id: 'emp-alpha',
        x: 220,
        y: 130,
        radius: 26,
        color: '#00f0ff',
        isCharged: false,
        chargeTimer: 0,
        maxChargeTime: 3.0,
      },
      {
        id: 'emp-beta',
        x: 740,
        y: 130,
        radius: 26,
        color: '#ff00cc',
        isCharged: false,
        chargeTimer: 0,
        maxChargeTime: 3.0,
      },
      {
        id: 'emp-gamma',
        x: 480,
        y: 440,
        radius: 26,
        color: '#ffaa00',
        isCharged: false,
        chargeTimer: 0,
        maxChargeTime: 3.0,
      },
    ],
    threeStarLoops: 3,
    threeStarMinTime: 3.0,
  },

  // Level 9: 量子核心金庫 (The Omega Vault)
  {
    id: 9,
    name: '量子核心金庫',
    subName: 'THE OMEGA VAULT',
    description: '終極因果律考驗！雙激光巡邏死角 + 三聯動重力閘門。四影跨時空同步協調，唯有時空特工方能登峰造極！',
    maxLoops: 4,
    loopDuration: 12.0,
    spawn: { x: 100, y: 270, angle: 0 },
    core: { x: 860, y: 270 },
    exit: { x: 100, y: 440 },
    walls: [
      // 外框
      { x: 0, y: 0, w: 960, h: 40 },
      { x: 0, y: 500, w: 960, h: 40 },
      { x: 0, y: 0, w: 40, h: 540 },
      { x: 920, y: 0, w: 40, h: 540 },
      // 隔間 1
      { x: 280, y: 40, w: 24, h: 170 },
      { x: 280, y: 330, w: 24, h: 170 },
      // 隔間 2
      { x: 520, y: 40, w: 24, h: 170 },
      { x: 520, y: 330, w: 24, h: 170 },
      // 隔間 3 (核心金庫)
      { x: 740, y: 40, w: 24, h: 170 },
      { x: 740, y: 330, w: 24, h: 170 },
    ],
    pads: [
      {
        id: 'pad-gate-1',
        x: 180,
        y: 110,
        radius: 24,
        targets: ['door-omega-1'],
        isPressed: false,
        holdTimer: 0,
        color: '#00f0ff',
      },
      {
        id: 'pad-gate-2',
        x: 400,
        y: 430,
        radius: 24,
        targets: ['door-omega-2'],
        isPressed: false,
        holdTimer: 0,
        color: '#ff00cc',
      },
      {
        id: 'pad-gate-3',
        x: 640,
        y: 110,
        radius: 24,
        targets: ['door-omega-3'],
        isPressed: false,
        holdTimer: 0,
        color: '#ffaa00',
      },
    ],
    doors: [
      {
        id: 'door-omega-1',
        x: 280,
        y: 210,
        w: 24,
        h: 120,
        isOpen: false,
        openProgress: 0,
        orientation: 'vertical',
      },
      {
        id: 'door-omega-2',
        x: 520,
        y: 210,
        w: 24,
        h: 120,
        isOpen: false,
        openProgress: 0,
        orientation: 'vertical',
      },
      {
        id: 'door-omega-3',
        x: 740,
        y: 210,
        w: 24,
        h: 120,
        isOpen: false,
        openProgress: 0,
        orientation: 'vertical',
      },
    ],
    lasers: [
      // 雙巡邏雷射 1：垂直上下巡弋
      {
        id: 'patrol-laser-1',
        x1: 400,
        y1: 180,
        x2: 400,
        y2: 360,
        isActive: true,
        patrol: {
          axis: 'y',
          range: 60,
          speed: 2.2,
        },
      },
      // 雙巡邏雷射 2：橫向左右巡弋
      {
        id: 'patrol-laser-2',
        x1: 590,
        y1: 270,
        x2: 690,
        y2: 270,
        isActive: true,
        patrol: {
          axis: 'x',
          range: 45,
          speed: 2.6,
        },
      },
    ],
    threeStarLoops: 3,
    threeStarMinTime: 2.5,
  },

  // Level 10: 重力反轉矩陣 (Gravity Inversion)
  {
    id: 10,
    name: '重力反轉矩陣',
    subName: 'GRAVITY INVERSION',
    description: '時空重力場極性顛倒！踩下重力反轉板改變全場極性：常開的致命激光休眠，反極性安全門由關變開！殘影踩住踏板引導極性反轉，本體穿過解鎖力場通路。',
    maxLoops: 3,
    loopDuration: 12.0,
    spawn: { x: 120, y: 440, angle: -Math.PI / 2 },
    core: { x: 840, y: 110 },
    exit: { x: 120, y: 110 },
    walls: [
      // 外框
      { x: 0, y: 0, w: 960, h: 40 },
      { x: 0, y: 500, w: 960, h: 40 },
      { x: 0, y: 0, w: 40, h: 540 },
      { x: 920, y: 0, w: 40, h: 540 },
      // 左側豎牆
      { x: 260, y: 40, w: 24, h: 200 },
      { x: 260, y: 330, w: 24, h: 170 },
      // 中央縱向與橫向隔離壁
      { x: 540, y: 160, w: 24, h: 340 },
      { x: 284, y: 160, w: 256, h: 24 },
      // 右側室隔離
      { x: 740, y: 40, w: 24, h: 160 },
      { x: 740, y: 290, w: 24, h: 210 },
    ],
    pads: [
      {
        id: 'pad-gravity',
        x: 400,
        y: 430,
        radius: 26,
        targets: [],
        isPressed: false,
        holdTimer: 0,
        color: '#c040ff',
        isGravityInverter: true,
      },
      {
        id: 'pad-core-gate',
        x: 400,
        y: 100,
        radius: 24,
        targets: ['door-core-gate'],
        isPressed: false,
        holdTimer: 0,
        color: '#00f0ff',
      },
    ],
    doors: [
      {
        id: 'door-polar-1',
        x: 260,
        y: 240,
        w: 24,
        h: 90,
        isOpen: false,
        openProgress: 0,
        orientation: 'vertical',
        inverted: true,
      },
      {
        id: 'door-core-gate',
        x: 740,
        y: 200,
        w: 24,
        h: 90,
        isOpen: false,
        openProgress: 0,
        orientation: 'vertical',
      },
    ],
    lasers: [
      {
        id: 'laser-polar-1',
        x1: 284,
        y1: 280,
        x2: 540,
        y2: 280,
        isActive: true,
        inverted: true,
      },
      {
        id: 'laser-polar-2',
        x1: 650,
        y1: 40,
        x2: 650,
        y2: 320,
        isActive: true,
        inverted: true,
      },
      {
        id: 'laser-timed-1',
        x1: 764,
        y1: 200,
        x2: 920,
        y2: 200,
        isActive: true,
        cycleTime: 2.4,
        onDuration: 1.2,
        offDuration: 1.2,
        timer: 0,
      },
    ],
    threeStarLoops: 2,
    threeStarMinTime: 3.5,
  },

  // Level 11: 稜鏡折射陣列 (Laser Prism Lattice)
  {
    id: 11,
    name: '稜鏡折射陣列',
    subName: 'LASER PRISM LATTICE',
    description: '中央防爆金庫大門厚達數米，唯有將高能致命雷射偏折聚焦方能將其熔斷！殘影踩上稜鏡調校踏板推動光學稜鏡，將縱向雷射 90 度折射直擊防爆大門控制核心！',
    maxLoops: 3,
    loopDuration: 12.0,
    spawn: { x: 120, y: 270, angle: 0 },
    core: { x: 840, y: 270 },
    exit: { x: 840, y: 440 },
    walls: [
      // 外框
      { x: 0, y: 0, w: 960, h: 40 },
      { x: 0, y: 500, w: 960, h: 40 },
      { x: 0, y: 0, w: 40, h: 540 },
      { x: 920, y: 0, w: 40, h: 540 },
      // 上方雷射發電室外牆
      { x: 360, y: 40, w: 24, h: 140 },
      // 防爆金庫大門兩側厚牆
      { x: 680, y: 40, w: 24, h: 160 },
      { x: 680, y: 320, w: 24, h: 180 },
      // 調校室通道分隔牆
      { x: 260, y: 360, w: 320, h: 24 },
    ],
    pads: [
      {
        id: 'pad-prism-align',
        x: 420,
        y: 440,
        radius: 26,
        targets: [],
        isPressed: false,
        holdTimer: 0,
        color: '#00f0ff',
      },
      {
        id: 'pad-exit-vault',
        x: 840,
        y: 110,
        radius: 24,
        targets: ['door-exit-gate'],
        isPressed: false,
        holdTimer: 0,
        color: '#ffaa00',
      },
    ],
    doors: [
      {
        id: 'door-blast-vault',
        x: 680,
        y: 200,
        w: 24,
        h: 120,
        isOpen: false,
        openProgress: 0,
        orientation: 'vertical',
      },
      {
        id: 'door-exit-gate',
        x: 760,
        y: 360,
        w: 160,
        h: 24,
        isOpen: false,
        openProgress: 0,
        orientation: 'horizontal',
      },
    ],
    lasers: [
      {
        id: 'laser-emitter-1',
        x1: 480,
        y1: 40,
        x2: 480,
        y2: 260,
        isActive: true,
      },
      {
        id: 'laser-patrol-prism',
        x1: 240,
        y1: 180,
        x2: 240,
        y2: 320,
        isActive: true,
        patrol: {
          axis: 'x',
          range: 50,
          speed: 2.2,
        },
      },
    ],
    prisms: [
      {
        id: 'prism-1',
        x: 480,
        y: 260,
        radius: 24,
        targetDoorId: 'door-blast-vault',
        sourceLaserId: 'laser-emitter-1',
        requiresPadId: 'pad-prism-align',
        isAligned: false,
        color: '#00f0ff',
      },
    ],
    threeStarLoops: 2,
    threeStarMinTime: 3.0,
  },

  // Level 12: 終極奇異點核心 (The Singularity Paradox)
  {
    id: 12,
    name: '終極奇異點核心',
    subName: 'THE SINGULARITY PARADOX',
    description: '4 影跨時空同步協調的宏大時空交響樂！EMP 電磁癱瘓、重力極性反轉、光學稜鏡熔斷與交叉掃描激光矩陣。在奇異點坍縮最後 12 秒內壓哨完成大撤離！',
    maxLoops: 4,
    loopDuration: 12.0,
    spawn: { x: 100, y: 440, angle: -Math.PI / 2 },
    core: { x: 500, y: 270 },
    exit: { x: 860, y: 100 },
    walls: [
      // 外框
      { x: 0, y: 0, w: 960, h: 40 },
      { x: 0, y: 500, w: 960, h: 40 },
      { x: 0, y: 0, w: 40, h: 540 },
      { x: 920, y: 0, w: 40, h: 540 },
      // 奇異點金庫四方環
      { x: 330, y: 150, w: 24, h: 240 },
      { x: 650, y: 150, w: 24, h: 240 },
      { x: 330, y: 150, w: 110, h: 24 },
      { x: 550, y: 150, w: 124, h: 24 },
      { x: 330, y: 366, w: 110, h: 24 },
      { x: 550, y: 366, w: 124, h: 24 },
    ],
    pads: [
      {
        id: 'pad-sing-gravity',
        x: 160,
        y: 120,
        radius: 26,
        targets: [],
        isPressed: false,
        holdTimer: 0,
        color: '#c040ff',
        isGravityInverter: true,
      },
      {
        id: 'pad-prism-sing',
        x: 740,
        y: 270,
        radius: 24,
        targets: [],
        isPressed: false,
        holdTimer: 0,
        color: '#ffe600',
      },
    ],
    doors: [
      {
        id: 'door-sing-north',
        x: 440,
        y: 150,
        w: 110,
        h: 24,
        isOpen: false,
        openProgress: 0,
        orientation: 'horizontal',
        inverted: true,
      },
      {
        id: 'door-sing-east',
        x: 650,
        y: 215,
        w: 24,
        h: 110,
        isOpen: false,
        openProgress: 0,
        orientation: 'vertical',
      },
    ],
    lasers: [
      {
        id: 'laser-sing-beam',
        x1: 500,
        y1: 40,
        x2: 500,
        y2: 90,
        isActive: true,
      },
      {
        id: 'laser-sing-polar',
        x1: 674,
        y1: 150,
        x2: 920,
        y2: 150,
        isActive: true,
        inverted: true,
      },
      {
        id: 'laser-sing-patrol-1',
        x1: 220,
        y1: 180,
        x2: 330,
        y2: 180,
        isActive: true,
        patrol: {
          axis: 'y',
          range: 50,
          speed: 2.5,
        },
      },
    ],
    empTerminals: [
      {
        id: 'emp-sing-1',
        x: 140,
        y: 280,
        radius: 24,
        color: '#00f0ff',
        isCharged: false,
        chargeTimer: 0,
        maxChargeTime: 3.5,
      },
      {
        id: 'emp-sing-2',
        x: 820,
        y: 420,
        radius: 24,
        color: '#ff00cc',
        isCharged: false,
        chargeTimer: 0,
        maxChargeTime: 3.5,
      },
    ],
    prisms: [
      {
        id: 'prism-sing',
        x: 500,
        y: 90,
        radius: 22,
        targetDoorId: 'door-sing-east',
        sourceLaserId: 'laser-sing-beam',
        requiresPadId: 'pad-prism-sing',
        isAligned: false,
        color: '#ffe600',
      },
    ],
    threeStarLoops: 3,
    threeStarMinTime: 2.0,
  },
];

